-- Adminer 5.4.0 PostgreSQL 16.13 dump

DROP TABLE IF EXISTS "movement_log";
CREATE TABLE "public"."movement_log" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "bluetooth_id" text NOT NULL,
    "timestamp_movement" timestamptz DEFAULT now(),
    "from_zone_id" integer,
    "to_zone_id" integer,
    "deciding_rssi" numeric(6,2),
    CONSTRAINT "movement_log_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

INSERT INTO "movement_log" ("id", "bluetooth_id", "timestamp_movement", "from_zone_id", "to_zone_id", "deciding_rssi") VALUES
(15952,	'DC:0D:30:48:30:2F',	'2026-03-11 09:40:28.351293+00',	1,	NULL,	-999.00),
(15953,	'DC:0D:30:48:30:2F',	'2026-03-11 09:40:30.351047+00',	NULL,	1,	-88.34),
(15954,	'DC:0D:30:48:30:2F',	'2026-03-11 10:21:29.820487+00',	1,	NULL,	-999.00),
(15955,	'DC:0D:30:48:30:2F',	'2026-03-11 10:21:31.819805+00',	NULL,	1,	-89.79),
(15956,	'DC:0D:30:48:30:2F',	'2026-03-11 12:46:24.030332+00',	1,	NULL,	-999.00),
(15957,	'DC:0D:30:48:30:2F',	'2026-03-11 12:46:28.032029+00',	NULL,	1,	-87.97),
(15958,	'DC:0D:30:48:30:2F',	'2026-03-11 13:04:56.683071+00',	1,	NULL,	-999.00),
(15959,	'DC:0D:30:48:30:2F',	'2026-03-11 13:04:58.68239+00',	NULL,	1,	-87.96),
(15960,	'DC:0D:30:48:30:2F',	'2026-03-11 13:07:28.771796+00',	1,	NULL,	-999.00),
(15961,	'DC:0D:30:48:30:2F',	'2026-03-11 13:07:32.772807+00',	NULL,	1,	-89.59),
(15962,	'DC:0D:30:48:30:2F',	'2026-03-11 13:31:31.617935+00',	1,	NULL,	-999.00),
(15963,	'DC:0D:30:48:30:2F',	'2026-03-11 13:31:33.618272+00',	NULL,	1,	-86.18),
(15964,	'DC:0D:30:48:30:2F',	'2026-03-11 14:07:42.88282+00',	1,	NULL,	-999.00),
(15965,	'DC:0D:30:48:30:2F',	'2026-03-11 14:07:44.882557+00',	NULL,	1,	-88.25),
(15966,	'DC:0D:30:48:30:2F',	'2026-03-11 14:20:29.335671+00',	1,	NULL,	-999.00),
(15967,	'DC:0D:30:48:30:2F',	'2026-03-11 14:20:31.334859+00',	NULL,	1,	-87.86),
(15968,	'DC:0D:30:48:30:2F',	'2026-03-11 14:59:14.620128+00',	1,	NULL,	-999.00),
(15969,	'DC:0D:30:48:30:2F',	'2026-03-11 14:59:16.619108+00',	NULL,	1,	-90.01),
(15970,	'DC:0D:30:48:30:2F',	'2026-03-11 17:20:47.379323+00',	1,	NULL,	-999.00),
(15971,	'DC:0D:30:48:30:2F',	'2026-03-11 17:20:49.378622+00',	NULL,	1,	-87.07),
(15972,	'DC:0D:30:48:30:2F',	'2026-03-11 18:05:58.894935+00',	1,	NULL,	-999.00),
(15973,	'DC:0D:30:48:30:2F',	'2026-03-11 18:06:04.896353+00',	NULL,	1,	-86.14),
(15974,	'DC:0D:30:48:30:2F',	'2026-03-11 18:36:23.933316+00',	1,	NULL,	-999.00),
(15975,	'DC:0D:30:48:30:2F',	'2026-03-11 18:36:25.932445+00',	NULL,	1,	-86.77),
(15976,	'DC:0D:30:48:30:2F',	'2026-03-11 19:08:25.024661+00',	1,	NULL,	-999.00),
(15977,	'DC:0D:30:48:30:2F',	'2026-03-11 19:08:27.024247+00',	NULL,	1,	-90.01),
(15978,	'DC:0D:30:48:30:2F',	'2026-03-11 23:34:17.988592+00',	1,	NULL,	-999.00),
(15979,	'DC:0D:30:48:30:2F',	'2026-03-11 23:34:21.990906+00',	NULL,	1,	-87.50),
(15980,	'DC:0D:30:48:30:2F',	'2026-03-11 23:41:58.27287+00',	1,	NULL,	-999.00),
(15981,	'DC:0D:30:48:30:2F',	'2026-03-11 23:42:00.272692+00',	NULL,	1,	-89.42),
(15982,	'DC:0D:30:48:30:2F',	'2026-03-12 02:45:00.73142+00',	1,	NULL,	-999.00),
(15983,	'DC:0D:30:48:30:2F',	'2026-03-12 02:45:04.732709+00',	NULL,	1,	-89.13),
(15984,	'DC:0D:30:48:30:2F',	'2026-03-12 03:19:53.971987+00',	1,	NULL,	-999.00),
(15985,	'DC:0D:30:48:30:2F',	'2026-03-12 03:19:55.971703+00',	NULL,	1,	-90.02),
(15986,	'DC:0D:30:48:30:2F',	'2026-03-12 05:02:21.613808+00',	1,	NULL,	-999.00),
(15987,	'DC:0D:30:48:30:2F',	'2026-03-12 05:02:23.614813+00',	NULL,	1,	-86.16),
(15988,	'DC:0D:30:48:30:2F',	'2026-03-12 05:32:04.670926+00',	1,	NULL,	-999.00),
(15989,	'DC:0D:30:48:30:2F',	'2026-03-12 05:32:06.670641+00',	NULL,	1,	-89.33),
(15990,	'DC:0D:30:48:30:2F',	'2026-03-12 05:34:50.766369+00',	1,	NULL,	-999.00),
(15991,	'DC:0D:30:48:30:2F',	'2026-03-12 05:34:52.766354+00',	NULL,	1,	-89.13),
(15992,	'DC:0D:30:48:30:2F',	'2026-03-12 05:48:47.259664+00',	1,	NULL,	-999.00),
(15993,	'DC:0D:30:48:30:2F',	'2026-03-12 05:48:49.259881+00',	NULL,	1,	-90.31),
(15994,	'DC:0D:30:49:0B:B1',	'2026-03-18 03:05:26.222553+00',	1,	NULL,	-999.00),
(15995,	'DC:0D:30:49:0B:B1',	'2026-03-18 03:05:46.232138+00',	NULL,	1,	-72.50),
(15996,	'DC:0D:30:48:30:2F',	'2026-03-21 15:20:00.636008+00',	1,	NULL,	-999.00),
(15997,	'DC:0D:30:48:30:2F',	'2026-03-21 15:20:04.636476+00',	NULL,	1,	-88.82),
(15998,	'DC:0D:30:48:30:2F',	'2026-03-23 14:33:20.097545+00',	1,	NULL,	-999.00),
(15999,	'DC:0D:30:48:30:2F',	'2026-03-23 14:33:32.101701+00',	NULL,	1,	-81.43),
(16000,	'DC:0D:30:48:30:2F',	'2026-02-05 03:33:35.585854+00',	1,	2,	-73.75),
(16001,	'DC:0D:30:49:0B:BD',	'2026-03-25 13:35:02.920331+00',	1,	2,	-70.06),
(16002,	'DC:0D:30:49:0B:B1',	'2026-03-25 13:35:30.938074+00',	1,	2,	-74.17),
(16003,	'DC:0D:30:49:0B:B1',	'2026-03-25 13:35:41.110555+00',	2,	1,	-70.66),
(16004,	'DC:0D:30:49:0B:BD',	'2026-03-25 13:45:59.468278+00',	2,	1,	-67.08),
(16005,	'DC:0D:30:49:0B:BD',	'2026-03-25 15:10:22.221744+00',	1,	2,	-75.10),
(16006,	'DC:0D:30:49:0B:BD',	'2026-03-25 15:11:54.428532+00',	2,	1,	-69.75),
(16007,	'DC:0D:30:49:0B:BD',	'2026-03-25 15:37:15.122614+00',	1,	2,	-69.84),
(16008,	'DC:0D:30:48:30:2F',	'2026-03-25 18:39:03.158924+00',	2,	1,	-65.00),
(16009,	'DC:0D:30:48:30:2F',	'2026-03-25 18:39:19.130369+00',	1,	2,	-74.73),
(16010,	'DC:0D:30:49:0B:B1',	'2026-03-25 21:55:10.00314+00',	1,	2,	-72.37),
(16011,	'DC:0D:30:49:0B:B1',	'2026-03-25 22:04:44.015716+00',	2,	1,	-65.59),
(16012,	'DC:0D:30:49:0B:BD',	'2026-03-26 17:34:42.65478+00',	2,	1,	-69.59),
(16013,	'DC:0D:30:48:30:2F',	'2026-03-27 00:19:48.062199+00',	2,	1,	-71.43),
(16014,	'DC:0D:30:48:30:2F',	'2026-03-27 00:20:00.870163+00',	1,	2,	-80.08),
(16015,	'DC:0D:30:48:30:2F',	'2026-03-27 23:11:03.463333+00',	2,	1,	-84.42);

DROP TABLE IF EXISTS "mst_asset";
CREATE TABLE "public"."mst_asset" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "bluetooth_id" text NOT NULL,
    "asset_name" text,
    "last_movement_dt" timestamptz,
    "distance_from_scanner" numeric(6,2),
    "created_at" timestamptz DEFAULT now(),
    "current_zone_id" integer,
    "extra" jsonb DEFAULT '{}',
    CONSTRAINT "mst_asset_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE UNIQUE INDEX mst_asset_bluetooth_id_key ON public.mst_asset USING btree (bluetooth_id);

INSERT INTO "mst_asset" ("id", "bluetooth_id", "asset_name", "last_movement_dt", "distance_from_scanner", "created_at", "current_zone_id", "extra") VALUES
(2,	'DC:0D:30:48:30:3B',	'Badge1-3B',	'2026-02-08 22:31:23.021149+00',	NULL,	'2026-01-05 07:47:02.989707+00',	NULL,	'{}'),
(20,	'DC:0D:30:4A:A5:C1',	'uae',	NULL,	NULL,	'2026-03-13 06:05:21.973707+00',	NULL,	'{}'),
(5,	'DC:0D:30:49:0B:B1',	'Oval2-B1',	'2026-03-25 22:04:44.015716+00',	NULL,	'2026-01-05 07:48:48.054273+00',	1,	'{"battery": 100, "is_alive": true, "last_seen": "2026-04-01T05:23:27.618565+00:00"}'),
(4,	'DC:0D:30:49:0B:BD',	'Oval1-BD',	'2026-03-26 17:34:42.65478+00',	NULL,	'2026-01-05 07:48:37.706816+00',	1,	'{"battery": 100, "is_alive": true, "last_seen": "2026-04-01T05:23:27.618565+00:00"}'),
(3,	'DC:0D:30:48:30:2F',	'Badge2-2F',	'2026-03-27 23:11:03.463333+00',	NULL,	'2026-01-05 07:48:06.017806+00',	1,	'{"battery": 100, "is_alive": true, "last_seen": "2026-04-01T05:23:27.618565+00:00"}'),
(22,	'DC:0D:30:26:C4:1C',	'1C',	NULL,	NULL,	'2026-03-23 15:09:29.557783+00',	NULL,	'{}');

DROP TABLE IF EXISTS "mst_master";
CREATE TABLE "public"."mst_master" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text,
    "mac" text NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    "ip" text DEFAULT '0.0.0.0',
    CONSTRAINT "mst_server_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE UNIQUE INDEX mst_server_mac_id_key ON public.mst_master USING btree (mac);

CREATE UNIQUE INDEX mst_master_mac_key ON public.mst_master USING btree (mac);

INSERT INTO "mst_master" ("id", "name", "mac", "created_at", "ip") VALUES
(2,	'Master Pi',	'88:A2:9E:57:A3:B0',	'2026-03-11 08:13:24.828533+00',	'192.168.1.158');

DROP TABLE IF EXISTS "mst_master_zone";
CREATE TABLE "public"."mst_master_zone" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mst_server_id" integer NOT NULL,
    "mst_zone_id" integer NOT NULL,
    CONSTRAINT "mst_server_zone_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE UNIQUE INDEX mst_server_zone_mst_server_id_mst_zone_id_key ON public.mst_master_zone USING btree (mst_server_id, mst_zone_id);


DROP TABLE IF EXISTS "mst_scanner";
CREATE TABLE "public"."mst_scanner" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mac_id" text NOT NULL,
    "name" text,
    "type" text DEFAULT 'Other',
    "created_at" timestamptz DEFAULT now(),
    "last_heartbeat" timestamptz,
    CONSTRAINT "mst_scanner_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE UNIQUE INDEX mst_scanner_mac_id_key ON public.mst_scanner USING btree (mac_id);

INSERT INTO "mst_scanner" ("id", "mac_id", "name", "type", "created_at", "last_heartbeat") VALUES
(2,	'68:25:DD:33:8D:C8',	'esp32 with scanner',	'ESP32',	'2025-12-29 12:10:30.408978+00',	NULL),
(17,	'39:4E:27:34:D8:C7',	'UAE Scanner',	'android',	'2026-03-13 06:10:55.379691+00',	NULL),
(18,	'12:21:14:C6:A7:6A',	'Google Pixel 7',	'android',	'2026-03-15 13:34:32.434703+00',	NULL),
(4,	'68:25:DD:32:92:D0',	'esp32 with master',	'esp32',	'2025-12-29 12:11:26.888619+00',	NULL),
(3,	'88:A2:9E:57:A3:0B',	'scanner',	'Pi3',	'2025-12-29 12:11:03.784294+00',	'2026-03-27 23:10:57.068235+00'),
(1,	'88:A2:9E:57:A3:B0',	'master scanner',	'RPi',	'2025-12-29 12:10:01.659586+00',	'2026-04-01 05:23:27.068235+00'),
(19,	'DF:E0:83:CB:F4:BF',	'LENOVO TB330XU',	'android',	'2026-03-23 15:05:52.593904+00',	NULL);

DROP TABLE IF EXISTS "mst_zone";
CREATE TABLE "public"."mst_zone" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "zone_name" text NOT NULL,
    "description" text,
    "dimension" jsonb,
    "created_at" timestamptz DEFAULT now(),
    CONSTRAINT "mst_zone_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE UNIQUE INDEX mst_zone_zone_name_key ON public.mst_zone USING btree (zone_name);

INSERT INTO "mst_zone" ("id", "zone_name", "description", "dimension", "created_at") VALUES
(1,	'ZONE_1',	'Room A',	NULL,	'2025-12-16 06:43:39.208402+00'),
(2,	'ZONE_2',	'Room B',	NULL,	'2025-12-16 06:43:39.208402+00'),
(9,	'UAE Test',	NULL,	NULL,	'2026-03-13 06:07:46.066733+00');

DROP TABLE IF EXISTS "mst_zone_scanner";
CREATE TABLE "public"."mst_zone_scanner" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mst_zone_id" integer NOT NULL,
    "mst_scanner_id" integer NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    CONSTRAINT "mst_zone_scanner_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE UNIQUE INDEX mst_zone_scanner_mst_zone_id_mst_scanner_id_key ON public.mst_zone_scanner USING btree (mst_zone_id, mst_scanner_id);

INSERT INTO "mst_zone_scanner" ("id", "mst_zone_id", "mst_scanner_id", "created_at") VALUES
(3,	2,	3,	'2025-12-17 05:48:14.626687+00'),
(2,	1,	4,	'2025-12-16 06:44:51.347348+00'),
(4,	2,	2,	'2025-12-19 07:51:57.054617+00'),
(5,	1,	1,	'2026-02-26 07:32:10.323222+00'),
(20,	9,	17,	'2026-03-13 06:12:26.154367+00');

ALTER TABLE ONLY "public"."movement_log" ADD CONSTRAINT "fk_movement_from_zone" FOREIGN KEY (from_zone_id) REFERENCES mst_zone(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."movement_log" ADD CONSTRAINT "fk_movement_to_zone" FOREIGN KEY (to_zone_id) REFERENCES mst_zone(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."mst_asset" ADD CONSTRAINT "fk_asset_zone" FOREIGN KEY (current_zone_id) REFERENCES mst_zone(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."mst_master_zone" ADD CONSTRAINT "fk_server_zone_server" FOREIGN KEY (mst_server_id) REFERENCES mst_master(id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."mst_master_zone" ADD CONSTRAINT "fk_server_zone_zone" FOREIGN KEY (mst_zone_id) REFERENCES mst_zone(id) ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."mst_zone_scanner" ADD CONSTRAINT "fk_zone_scanner_scanner" FOREIGN KEY (mst_scanner_id) REFERENCES mst_scanner(id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."mst_zone_scanner" ADD CONSTRAINT "fk_zone_scanner_zone" FOREIGN KEY (mst_zone_id) REFERENCES mst_zone(id) ON DELETE CASCADE NOT DEFERRABLE;

-- 2026-04-01 05:24:48 UTC
