@echo off
set PGPASSWORD=1234
echo --- FIXING mst_zone_scanner ---
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "ALTER TABLE mst_zone_scanner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "SELECT setval(pg_get_serial_sequence('mst_zone_scanner', 'id'), coalesce(max(id), 1)) FROM mst_zone_scanner;"
echo --- FIXING mst_master_zone ---
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "ALTER TABLE mst_master_zone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "SELECT setval(pg_get_serial_sequence('mst_master_zone', 'id'), coalesce(max(id), 1)) FROM mst_master_zone;"
echo --- FIXING mst_master ---
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "ALTER TABLE mst_master ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "SELECT setval(pg_get_serial_sequence('mst_master', 'id'), coalesce(max(id), 1)) FROM mst_master;"
echo --- VERIFYING ---
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "\d mst_zone_scanner"
