@echo off
set PGPASSWORD=1234
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "ALTER TABLE movement_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "SELECT setval(pg_get_serial_sequence('movement_log', 'id'), coalesce(max(id), 1)) FROM movement_log;"
