@echo off
set PGPASSWORD=1234
echo --- FIXING SCHEMA ---
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "ALTER TABLE mst_asset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "SELECT setval(pg_get_serial_sequence('mst_asset', 'id'), coalesce(max(id), 1)) FROM mst_asset;"

"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "ALTER TABLE mst_zone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "SELECT setval(pg_get_serial_sequence('mst_zone', 'id'), coalesce(max(id), 1)) FROM mst_zone;"

"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "ALTER TABLE mst_scanner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "SELECT setval(pg_get_serial_sequence('mst_scanner', 'id'), coalesce(max(id), 1)) FROM mst_scanner;"

echo --- VERIFYING ---
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d asset_tracking -h localhost -c "\d mst_asset"
